### ISSUE TITLE
Call-time pass-by-reference fatal error in PHP 5.4

### ISSUE THREAD

**Issue by bcobin** [eileenmcnaughton/org.civicrm.multisite#4]
Upgrade to PHP 5.4 produces the below, with fatal CiviCRM crash, even after upgrade to 2.3. I need to upgrade to PHP 5.4 for Drush, so I'll need to disable the module for now - just thought this should be noted.

This is with Civi 4.3.4, BTW.

Thanks!

---

Fatal error: Call-time pass-by-reference has been removed in /home/[site]/public_html/sites/default/files/civicrm/extensions/org.civicrm.multisite/multisite.php on line 249

**Comment by MegaphoneJon** [comment]
Hi bcobin - this bug was fixed in the master branch a while back, so you can install directly from Github to avoid that issue.  Alternatively, you can fix this simply by deleting an ampersand, see here: https://github.com/eileenmcnaughton/org.civicrm.multisite/commit/242d6e89ab8710b2ac6c3d8186fc7343fe265957

**Comment by eileenmcnaughton** [comment]
Ah thanks Jon. I looked & didn't see it & wondered why! I'll tag a new release

**Comment by bcobin** [comment]
Thanks, both - I'm embarrassed to say that I still haven't been able to get my head 'round Github; I would have thought that a simple update would have done the trick, but I guess that's what Eileen is talking about.

Regardless, thanks much!

**Comment by eileenmcnaughton** [comment]
For reasons that aren't immediately clear to me the civicrm extension thingee is rejecting it as 
In info.xml, the element ("version") is missing or invalid.

**Comment by MegaphoneJon** [comment]
Eileen, let me know if you want me to troubleshoot the extension directory issue.

**Comment by eileenmcnaughton** [comment]
yes please! I'm not spotting the problem here is the email I got

This is a message from the automated release system on civicrm.org.
Congratulations on releasing version v2.4 of extension 'Multisite
Permissioning'.

Unfortunately we have found a few errors while processing your release:
    - In info.xml, the element ("version") is missing or invalid.
    - The version numbers in the info.xml ("") and in the git tag ("2.4") do
not match.

You will need to correct these errors before we can accept this release.

Further help is available in the wiki at
http://wiki.civicrm.org/confluence/display/CRMDOC/Publish+an+Extension.

You can also request help in the Extensions community forum at
http://forum.civicrm.org/index.php/board,57.0.html.

Thank you so much for being an active contributor to CiviCRM and our
community.

**Comment by MegaphoneJon** [comment]
Hmm - I just manually published it, and the info.xml parser had no trouble whatsoever.  My guess is that there's a problem with the code that finds info.xml, and there's bad error checking?

**Comment by eileenmcnaughton** [comment]
published is published is published :-)
